# =============================================================================
# Logwell Production Docker Compose
# =============================================================================
# Full production stack with app and database.
#
# Required Environment Variables:
#   BETTER_AUTH_SECRET - Auth secret (min 32 chars). Generate: openssl rand -base64 32
#   ADMIN_PASSWORD     - Admin user password (min 8 chars)
#   ORIGIN             - Production URL (e.g., https://logs.example.com)
#
# Optional Environment Variables:
#   DB_PASSWORD - Database password (default: logwell_internal_db)
#                 Set this if exposing port 5432 for backups
#   PORT        - App port (default: 3000)
#
# Usage:
#   export BETTER_AUTH_SECRET=$(openssl rand -base64 32)
#   export ADMIN_PASSWORD="your-secure-password"
#   docker compose -f compose.prod.yaml up -d
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # Application Service
  # ---------------------------------------------------------------------------
  app:
    image: ghcr.io/divkix/logwell:dev
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - DATABASE_URL=postgresql://logwell:${DB_PASSWORD:-logwell_internal_db}@db:5432/logwell
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:?BETTER_AUTH_SECRET is required}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:?ADMIN_PASSWORD is required}
      - ORIGIN=${ORIGIN:?ORIGIN is required}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
    networks:
      - logwell-network

  # ---------------------------------------------------------------------------
  # PostgreSQL Database
  # ---------------------------------------------------------------------------
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: logwell
      POSTGRES_PASSWORD: ${DB_PASSWORD:-logwell_internal_db}
      POSTGRES_DB: logwell
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U logwell -d logwell"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - logwell-network
    # Uncomment to expose database port externally (not recommended for production)
    # ports:
    #   - "5432:5432"

# -----------------------------------------------------------------------------
# Volumes
# -----------------------------------------------------------------------------
volumes:
  postgres-data:
    driver: local

# -----------------------------------------------------------------------------
# Networks
# -----------------------------------------------------------------------------
networks:
  logwell-network:
    driver: bridge
