# =============================================================================
# sv-logger Production Docker Compose
# =============================================================================
# Full production stack with app, database, and optional reverse proxy
#
# Usage:
#   # Start the stack
#   docker compose -f compose.prod.yaml up -d
#
#   # View logs
#   docker compose -f compose.prod.yaml logs -f
#
#   # Stop the stack
#   docker compose -f compose.prod.yaml down
#
#   # Rebuild and restart
#   docker compose -f compose.prod.yaml up -d --build
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # Application Service
  # ---------------------------------------------------------------------------
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - DATABASE_URL=postgresql://svlogger:${DB_PASSWORD:-changeme}@db:5432/svlogger
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:?BETTER_AUTH_SECRET is required}
      - ORIGIN=${ORIGIN:-http://localhost:3000}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
    networks:
      - svlogger-network

  # ---------------------------------------------------------------------------
  # PostgreSQL Database
  # ---------------------------------------------------------------------------
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: svlogger
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      POSTGRES_DB: svlogger
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U svlogger -d svlogger"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - svlogger-network
    # Uncomment to expose database port externally (not recommended for production)
    # ports:
    #   - "5432:5432"

# -----------------------------------------------------------------------------
# Volumes
# -----------------------------------------------------------------------------
volumes:
  postgres-data:
    driver: local

# -----------------------------------------------------------------------------
# Networks
# -----------------------------------------------------------------------------
networks:
  svlogger-network:
    driver: bridge
